language: python
python:
  - "2.7"
  - "3.3"
notifications:
  email: false
before_install:
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - pip install numpy cython python-dateutil
install:
  - python setup.py build
  - python setup.py install
script: 
  - cd test
  - python run_all.py
