language: python

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0"
    - NO_NET=1
    - MPI=0

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - env: MPI=1
  include:
    # Absolute minimum dependencies.
    - python: 2.7
      env:
        - DEPENDS="numpy==1.9.0 cython==0.21 ordereddict==1.1 setuptools==18.0"
    # test MPI
    - python: 2.7
      env: 
        - MPI=1
        - CC=mpicc
        - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0 mpi4py>=1.3.1"
        - NETCDF_VERSION=4.4.1.1
        - NETCDF_DIR=$HOME/netcdf-${NETCDF_VERSION}
        - PATH=${NETCDF_DIR}/bin:${PATH} # pick up nc-config here
      addons:
        apt:
          packages:
            - openmpi-bin         # 1.6.5 based on trusty
            - libopenmpi-dev
            - libhdf5-openmpi-dev # 1.8.11 based on trusty

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - if [ $MPI -eq 1 ] ; then ci/travis/build-netcdf-parallel.sh; fi
  - python setup.py build
  - python setup.py install

script:
  - |
    if [ $MPI -eq 1 ] ; then
       cd examples
       pwd
       ls -l mpi_example.py
       mpirun -np 4 python mpi_example.py
       cd ..
    fi
  - cd test
  - python run_all.py
