environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    - TARGET_ARCH: x64
      CONDA_NPY: 114
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

    - TARGET_ARCH: x64
      CONDA_NPY: 114
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    # credits: JuliaLang developers.
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
         https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
         Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
           throw "There are newer queued builds for this pull request, failing early." }

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true --set auto_update_conda false
    - cmd: conda update conda
    # We need to pin conda until https://github.com/conda/conda/issues/6556 is fixed.
    - cmd: conda config --system --add pinned_packages defaults::conda
    - cmd: conda config --add channels conda-forge --force

    # Install conda-build.
    - cmd: conda install conda-build

    - cmd: set PYTHONUNBUFFERED=1
  
    - cmd: conda install vs2008_express_vc_python_patch
    - cmd: call setup_x64.bat
  
    - cmd: conda info --all

# Skip .NET project specific build phase.
build: off

test_script:
    - conda build conda.recipe
